services:
  caddy:
    build: ./caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./sites:/srv:ro
    networks:
      - appnetwork
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${DOMAINS}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  php-fpm:
    build: ./php
    container_name: php-fpm
    restart: always
    volumes:
      - ./sites:/srv
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - appnetwork
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL

networks:
  appnetwork:
    driver: bridge